/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_darielsevilla;

import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    private Administrador administrador;
    private Usuario actual = new Artista();
    private int modify = 0;
    private int referencia = 0;
    private int cualCrear = 0;
    private int cuantasCanciones = 0;

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        administrador = new Administrador("./usuarios.txt", "./lanzamientos.txt", "./canciones.txt", "./listas.txt", "./bitacora.txt");
        administrador.cargarArchivos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        wd_Artista = new javax.swing.JFrame();
        pn_Artista = new javax.swing.JPanel();
        lb_nombreArtista = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jt_lanzamientos = new javax.swing.JTree();
        mb_menu = new javax.swing.JMenuBar();
        mi_crudUsuarios = new javax.swing.JMenu();
        mmi_listEliminar = new javax.swing.JMenuItem();
        mmi_modificar = new javax.swing.JMenuItem();
        mmi_Eliminar = new javax.swing.JMenuItem();
        mi_crudLanzamiento = new javax.swing.JMenu();
        mmi_createSingle = new javax.swing.JMenuItem();
        mmi_crearLanzamiento = new javax.swing.JMenuItem();
        wd_Cliente = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        mb_menu2 = new javax.swing.JMenuBar();
        jd_register = new javax.swing.JDialog();
        pn_register = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        tf_pass = new javax.swing.JTextField();
        tf_artName = new javax.swing.JTextField();
        tf_usuario = new javax.swing.JTextField();
        sp_edad = new javax.swing.JSpinner();
        bt_create = new javax.swing.JButton();
        jd_listar = new javax.swing.JDialog();
        pn_listar = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_listar = new javax.swing.JList<>();
        bt_eliminar = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jd_crearCancion = new javax.swing.JDialog();
        jPanel2 = new javax.swing.JPanel();
        lb_titleSingles = new javax.swing.JLabel();
        tf_referencia = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        tf_titulo = new javax.swing.JTextField();
        sp_referencia = new javax.swing.JSpinner();
        tf_tiempo = new javax.swing.JTextField();
        bt_newSong = new javax.swing.JButton();
        jd_crearSingle = new javax.swing.JDialog();
        jPanel3 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        tf_lanzaId = new javax.swing.JTextField();
        tf_lanzaName = new javax.swing.JTextField();
        dc_lanzamiento = new com.toedter.calendar.JDateChooser();
        bt_nuevaCancion = new javax.swing.JButton();
        bt_crearLanzamiento = new javax.swing.JButton();
        pn_login = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreUsuario = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        bt_logIn = new javax.swing.JButton();
        bt_logIn1 = new javax.swing.JButton();

        pn_Artista.setBackground(new java.awt.Color(0, 0, 0));
        pn_Artista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nombreArtista.setBackground(new java.awt.Color(0, 204, 0));
        lb_nombreArtista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_nombreArtista.setForeground(new java.awt.Color(0, 204, 0));
        lb_nombreArtista.setText("Artista");
        pn_Artista.add(lb_nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 86, 39));

        jt_lanzamientos.setBackground(new java.awt.Color(255, 255, 255));
        jt_lanzamientos.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        jt_lanzamientos.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jt_lanzamientos);

        pn_Artista.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 436, -1));

        mi_crudUsuarios.setText("Usuarios");

        mmi_listEliminar.setText("Listar");
        mmi_listEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_listEliminarActionPerformed(evt);
            }
        });
        mi_crudUsuarios.add(mmi_listEliminar);

        mmi_modificar.setText("modificar");
        mmi_modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_modificarActionPerformed(evt);
            }
        });
        mi_crudUsuarios.add(mmi_modificar);

        mmi_Eliminar.setText("Eliminar");
        mmi_Eliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_EliminarActionPerformed(evt);
            }
        });
        mi_crudUsuarios.add(mmi_Eliminar);

        mb_menu.add(mi_crudUsuarios);

        mi_crudLanzamiento.setText("Lanzamientos");

        mmi_createSingle.setText("crear Single");
        mmi_createSingle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                mmi_createSingleMouseClicked(evt);
            }
        });
        mmi_createSingle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_createSingleActionPerformed(evt);
            }
        });
        mi_crudLanzamiento.add(mmi_createSingle);

        mmi_crearLanzamiento.setText("crear Album");
        mmi_crearLanzamiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mmi_crearLanzamientoActionPerformed(evt);
            }
        });
        mi_crudLanzamiento.add(mmi_crearLanzamiento);

        mb_menu.add(mi_crudLanzamiento);

        wd_Artista.setJMenuBar(mb_menu);

        javax.swing.GroupLayout wd_ArtistaLayout = new javax.swing.GroupLayout(wd_Artista.getContentPane());
        wd_Artista.getContentPane().setLayout(wd_ArtistaLayout);
        wd_ArtistaLayout.setHorizontalGroup(
            wd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        wd_ArtistaLayout.setVerticalGroup(
            wd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Artista, javax.swing.GroupLayout.DEFAULT_SIZE, 440, Short.MAX_VALUE)
        );

        wd_Cliente.setPreferredSize(new java.awt.Dimension(602, 440));

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 602, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 439, Short.MAX_VALUE)
        );

        wd_Cliente.setJMenuBar(mb_menu2);

        javax.swing.GroupLayout wd_ClienteLayout = new javax.swing.GroupLayout(wd_Cliente.getContentPane());
        wd_Cliente.getContentPane().setLayout(wd_ClienteLayout);
        wd_ClienteLayout.setHorizontalGroup(
            wd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        wd_ClienteLayout.setVerticalGroup(
            wd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_register.setBackground(new java.awt.Color(0, 0, 0));
        pn_register.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setForeground(new java.awt.Color(0, 204, 0));
        jLabel3.setText("Usuario:");
        pn_register.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 81, -1, -1));

        jLabel4.setForeground(new java.awt.Color(0, 204, 0));
        jLabel4.setText("Contraseña:");
        pn_register.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 125, -1, -1));

        jLabel5.setForeground(new java.awt.Color(0, 204, 0));
        jLabel5.setText("Es artista? Ingrese nombre Artistico:");
        pn_register.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, -1, -1));

        jLabel6.setForeground(new java.awt.Color(0, 204, 0));
        jLabel6.setText("Edad:");
        pn_register.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 159, -1, -1));

        tf_pass.setBackground(new java.awt.Color(255, 255, 255));
        pn_register.add(tf_pass, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 340, -1));

        tf_artName.setBackground(new java.awt.Color(255, 255, 255));
        pn_register.add(tf_artName, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 270, 340, -1));

        tf_usuario.setBackground(new java.awt.Color(255, 255, 255));
        pn_register.add(tf_usuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 80, 340, -1));

        sp_edad.setValue(12);
        pn_register.add(sp_edad, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 160, -1, -1));

        bt_create.setBackground(new java.awt.Color(0, 204, 0));
        bt_create.setForeground(new java.awt.Color(0, 0, 0));
        bt_create.setText("crear");
        bt_create.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_createMouseClicked(evt);
            }
        });
        pn_register.add(bt_create, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 350, -1, -1));

        javax.swing.GroupLayout jd_registerLayout = new javax.swing.GroupLayout(jd_register.getContentPane());
        jd_register.getContentPane().setLayout(jd_registerLayout);
        jd_registerLayout.setHorizontalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_register, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jd_registerLayout.setVerticalGroup(
            jd_registerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_register, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pn_listar.setBackground(new java.awt.Color(0, 0, 0));
        pn_listar.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jl_listar.setBackground(new java.awt.Color(255, 255, 255));
        jl_listar.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_listar);

        pn_listar.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, 240, 279));

        bt_eliminar.setBackground(new java.awt.Color(255, 0, 0));
        bt_eliminar.setForeground(new java.awt.Color(0, 0, 0));
        bt_eliminar.setText("Eliminar");
        bt_eliminar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_eliminarMouseClicked(evt);
            }
        });
        pn_listar.add(bt_eliminar, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        jButton3.setBackground(new java.awt.Color(0, 204, 0));
        jButton3.setForeground(new java.awt.Color(0, 0, 0));
        jButton3.setText("Regresar");
        jButton3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton3MouseClicked(evt);
            }
        });
        pn_listar.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 290, -1, -1));

        javax.swing.GroupLayout jd_listarLayout = new javax.swing.GroupLayout(jd_listar.getContentPane());
        jd_listar.getContentPane().setLayout(jd_listarLayout);
        jd_listarLayout.setHorizontalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_listarLayout.setVerticalGroup(
            jd_listarLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_listar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(0, 0, 0));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_titleSingles.setBackground(new java.awt.Color(0, 204, 0));
        lb_titleSingles.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lb_titleSingles.setForeground(new java.awt.Color(0, 255, 0));
        lb_titleSingles.setText("Crear cancion");
        jPanel2.add(lb_titleSingles, new org.netbeans.lib.awtextra.AbsoluteConstraints(6, 6, -1, 36));

        tf_referencia.setBackground(new java.awt.Color(0, 204, 0));
        tf_referencia.setForeground(new java.awt.Color(0, 255, 0));
        tf_referencia.setText("Referencia:");
        jPanel2.add(tf_referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 170, -1, -1));

        jLabel8.setBackground(new java.awt.Color(0, 204, 0));
        jLabel8.setForeground(new java.awt.Color(0, 255, 0));
        jLabel8.setText("Titulo:");
        jPanel2.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 60, -1, -1));

        jLabel9.setBackground(new java.awt.Color(0, 204, 0));
        jLabel9.setForeground(new java.awt.Color(0, 255, 0));
        jLabel9.setText("Tiempo de Duracion:");
        jPanel2.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 110, -1, -1));

        tf_titulo.setBackground(new java.awt.Color(255, 255, 255));
        tf_titulo.setForeground(new java.awt.Color(0, 0, 0));
        jPanel2.add(tf_titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 230, -1));
        jPanel2.add(sp_referencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, -1, -1));

        tf_tiempo.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.add(tf_tiempo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 110, 180, -1));

        bt_newSong.setBackground(new java.awt.Color(0, 204, 0));
        bt_newSong.setForeground(new java.awt.Color(0, 0, 0));
        bt_newSong.setText("Crear");
        bt_newSong.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_newSongMouseClicked(evt);
            }
        });
        bt_newSong.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_newSongActionPerformed(evt);
            }
        });
        jPanel2.add(bt_newSong, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, -1, -1));

        javax.swing.GroupLayout jd_crearCancionLayout = new javax.swing.GroupLayout(jd_crearCancion.getContentPane());
        jd_crearCancion.getContentPane().setLayout(jd_crearCancionLayout);
        jd_crearCancionLayout.setHorizontalGroup(
            jd_crearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 425, Short.MAX_VALUE)
        );
        jd_crearCancionLayout.setVerticalGroup(
            jd_crearCancionLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
        );

        jPanel3.setBackground(new java.awt.Color(0, 0, 0));

        jLabel7.setBackground(new java.awt.Color(0, 204, 0));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(0, 204, 0));
        jLabel7.setText("Crear Lanzamiento");

        jLabel10.setBackground(new java.awt.Color(0, 204, 0));
        jLabel10.setForeground(new java.awt.Color(0, 204, 0));
        jLabel10.setText("Titulo:");

        jLabel11.setBackground(new java.awt.Color(0, 204, 0));
        jLabel11.setForeground(new java.awt.Color(0, 204, 0));
        jLabel11.setText("Id:");

        jLabel12.setBackground(new java.awt.Color(0, 204, 0));
        jLabel12.setForeground(new java.awt.Color(0, 204, 0));
        jLabel12.setText("Fecha de Lanzamiento:");

        tf_lanzaId.setBackground(new java.awt.Color(255, 255, 255));
        tf_lanzaId.setForeground(new java.awt.Color(0, 0, 0));

        tf_lanzaName.setBackground(new java.awt.Color(255, 255, 255));
        tf_lanzaName.setForeground(new java.awt.Color(0, 0, 0));

        dc_lanzamiento.setBackground(new java.awt.Color(255, 255, 255));

        bt_nuevaCancion.setBackground(new java.awt.Color(51, 153, 0));
        bt_nuevaCancion.setText("crear cancion");
        bt_nuevaCancion.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_nuevaCancionMouseClicked(evt);
            }
        });
        bt_nuevaCancion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bt_nuevaCancionActionPerformed(evt);
            }
        });

        bt_crearLanzamiento.setBackground(new java.awt.Color(51, 204, 0));
        bt_crearLanzamiento.setForeground(new java.awt.Color(0, 0, 0));
        bt_crearLanzamiento.setText("create");
        bt_crearLanzamiento.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_crearLanzamientoMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel11)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel10))
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(tf_lanzaId, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(tf_lanzaName, javax.swing.GroupLayout.PREFERRED_SIZE, 213, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(jPanel3Layout.createSequentialGroup()
                                        .addGap(50, 50, 50)
                                        .addComponent(dc_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(56, 56, 56)
                        .addComponent(bt_nuevaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(54, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(bt_crearLanzamiento)
                .addGap(25, 25, 25))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(36, 36, 36)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tf_lanzaName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(44, 44, 44)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(tf_lanzaId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(56, 56, 56)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel12)
                    .addComponent(dc_lanzamiento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48)
                .addComponent(bt_nuevaCancion, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(bt_crearLanzamiento)
                .addContainerGap(24, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jd_crearSingleLayout = new javax.swing.GroupLayout(jd_crearSingle.getContentPane());
        jd_crearSingle.getContentPane().setLayout(jd_crearSingleLayout);
        jd_crearSingleLayout.setHorizontalGroup(
            jd_crearSingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jd_crearSingleLayout.setVerticalGroup(
            jd_crearSingleLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        pn_login.setBackground(new java.awt.Color(0, 0, 0));
        pn_login.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("SPOTIFY");
        pn_login.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 14, -1, -1));
        pn_login.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 114, -1, -1));

        tf_nombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        pn_login.add(tf_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 305, -1));

        pf_password.setBackground(new java.awt.Color(255, 255, 255));
        pf_password.setForeground(new java.awt.Color(0, 0, 0));
        pn_login.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, -1));

        bt_logIn.setBackground(new java.awt.Color(0, 204, 0));
        bt_logIn.setForeground(new java.awt.Color(0, 0, 0));
        bt_logIn.setText("Register");
        bt_logIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_logIn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logInMouseClicked(evt);
            }
        });
        pn_login.add(bt_logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 280, 100, 30));

        bt_logIn1.setBackground(new java.awt.Color(0, 204, 0));
        bt_logIn1.setForeground(new java.awt.Color(0, 0, 0));
        bt_logIn1.setText("Log in");
        bt_logIn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        bt_logIn1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                bt_logIn1MouseClicked(evt);
            }
        });
        pn_login.add(bt_logIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 240, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_login, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 344, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    private void bt_logIn1MouseClicked(java.awt.event.MouseEvent evt) {                                       
        String usuario = tf_nombreUsuario.getText();
        String password = pf_password.getText();
        int cont = 0;
        boolean worked = false;
        for (Usuario u : administrador.getUsuarios()) {
            if (usuario.equals(u.getUsername())) {
                cont++;
                if (password.equals(u.getPassword())) {
                    actual = u;
                    worked = true;
                } else {
                    JOptionPane.showMessageDialog(this, "Password incorrecta");
                }
            }
        }

        if (cont == 0) {
            JOptionPane.showMessageDialog(this, "Usuario no encontrado");
        }
        if (worked) {
            if (actual instanceof Oyente) {
                iniciarVentanaCliente();
            } else {
                iniciarVentanaArtista();
            }
        }
    }                                      

    private void bt_createMouseClicked(java.awt.event.MouseEvent evt) {                                       
        int x = 0;
        System.out.println(x);
        for (Usuario u : administrador.getUsuarios()) {
            if (u.getUsername().equals(tf_usuario.getText()) && !u.equals(actual)) {
                x++;

                break;
            }
        }

        if (x == 0) {
            if (modify == 0) {
                if (!tf_artName.getText().equals("")) {
                    try {

                        Artista temp = new Artista(tf_usuario.getText(), tf_pass.getText(), ((int) sp_edad.getValue()), tf_artName.getText());
                        administrador.getUsuarios().add(temp);
                        administrador.writeUsuarios();
                        administrador.writeBitacora(temp);
                        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
                        jd_register.setVisible(false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(jd_register, "edad incorrecta");
                    }
                } else {
                    try {
                        Oyente temp = new Oyente(tf_usuario.getText(), tf_pass.getText(), ((int) sp_edad.getValue()));
                        administrador.getUsuarios().add(temp);
                        administrador.writeUsuarios();
                        administrador.writeBitacora(temp);
                        JOptionPane.showMessageDialog(null, "Usuario creado exitosamente");
                        jd_register.setVisible(false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(jd_register, "edad incorrecta");
                    }
                }

            } else if (modify == 1) {
                if (actual instanceof Artista) {
                    try {

                        actual.setUsername(tf_usuario.getText());
                        actual.setPassword(tf_pass.getText());
                        actual.setEdad(((int) sp_edad.getValue()));

                        ((Artista) actual).setEdad(((int) sp_edad.getValue()));

                        administrador.writeUsuarios();
                        JOptionPane.showMessageDialog(null, "Usuario modificado exitosamente");
                        modify--;
                        jd_register.setVisible(false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(jd_register, "edad incorrecta");
                    }
                } else {
                    try {
                        actual.setUsername(tf_usuario.getText());
                        actual.setPassword(tf_pass.getText());
                        actual.setEdad(((int) sp_edad.getValue()));

                        administrador.writeUsuarios();
                        JOptionPane.showMessageDialog(null, "Usuario modificado exitosamente");
                        modify--;
                        jd_register.setVisible(false);
                    } catch (Exception ex) {
                        JOptionPane.showMessageDialog(jd_register, "edad incorrecta");
                    }
                }
            }
        } else {
            JOptionPane.showMessageDialog(null, "Nombre Repetido");
        }
    }                                      

    private void bt_logInMouseClicked(java.awt.event.MouseEvent evt) {                                      
        iniciarJd_register();
    }                                     

    private void mmi_listEliminarActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        DefaultListModel m = (DefaultListModel) jl_listar.getModel();
        for (Usuario a : administrador.getUsuarios()) {
            m.addElement(a);
        }
        iniciarjd_listar();
    }                                                

    private void bt_eliminarMouseClicked(java.awt.event.MouseEvent evt) {                                         
        if (jl_listar.getSelectedIndex() != -1) {

        }
        this.setVisible(true);
    }                                        

    private void jButton3MouseClicked(java.awt.event.MouseEvent evt) {                                      
        // TODO add your handling code here:
    }                                     

    private void mmi_EliminarActionPerformed(java.awt.event.ActionEvent evt) {                                             
        int x = JOptionPane.showConfirmDialog(jd_listar, "Desea Eliminar este usuario?");

        if (x == JOptionPane.YES_OPTION) {
            administrador.getUsuarios().remove(actual);
            administrador.writeUsuarios();
            jd_listar.setVisible(false);
            wd_Cliente.setVisible(false);
            wd_Artista.setVisible(false);
            this.setVisible(true);

        }


    }                                            

    private void mmi_modificarActionPerformed(java.awt.event.ActionEvent evt) {                                              
        modify++;
        iniciarJd_register();
    }                                             

    private void mmi_crearLanzamientoActionPerformed(java.awt.event.ActionEvent evt) {                                                     
        cualCrear = 2;
        iniciarjd_crearSingle();
    }                                                    

    private void bt_newSongMouseClicked(java.awt.event.MouseEvent evt) {                                        
        boolean valid = true;
        while (valid) {
            try {
                Cancion c = new Cancion(tf_titulo.getText(), Integer.parseInt(tf_tiempo.getText()), referencia);
                administrador.getCanciones().add(c);
                administrador.writeCanciones();

                valid = false;
            } catch (Exception e) {
                JOptionPane.showMessageDialog(wd_Artista, "Ingrese valor valido");
            }
        }

        jd_crearCancion.setVisible(false);
        if (cuantasCanciones != 0) {
            iniciarCrearCancion();
        }
    }                                       

    private void mmi_createSingleActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        cualCrear = 1;
        iniciarjd_crearSingle();

    }                                                

    private void mmi_createSingleMouseClicked(java.awt.event.MouseEvent evt) {                                              
        // TODO add your handling code here:
    }                                             

    private void bt_crearLanzamientoMouseClicked(java.awt.event.MouseEvent evt) {                                                 
        boolean valid = true;
        while (valid) {
            try {
                referencia = Integer.parseInt(tf_lanzaId.getText());
                System.out.println(referencia);
                for (Lanzamiento l : administrador.getLanzamientos()) {
                    if (l.getId() == referencia) {
                        throw new Exception("Valor repetido");
                    }
                }

                if (cualCrear == 1) {
                    Single temp = new Single(tf_titulo.getText(), dc_lanzamiento.getDate(), 0, referencia, actual.getUsername());
                    for (Cancion c : administrador.getCanciones()) {
                        if (c.getAlbumPerteneciente() == temp.getId()) {
                            temp.setCancion(c);
                        }
                        administrador.getLanzamientos().add(temp);
                        ((Artista) actual).getLanzamiento().add(temp);
                        administrador.writeLanzamientos();
                        cualCrear = 0;
                    }
                }else if(cualCrear == 2){
                    Album temp = new Album(tf_titulo.getText(), dc_lanzamiento.getDate(), 0, referencia, actual.getUsername());
                    for (Cancion c : administrador.getCanciones()) {
                        if (c.getAlbumPerteneciente() == temp.getId()) {
                            temp.addCancion(c);
                        }
                        administrador.getLanzamientos().add(temp);
                        ((Artista) actual).getLanzamiento().add(temp);
                        administrador.writeLanzamientos();
                        cualCrear = 0;
                    }
                }
                valid = false;
                resetArtistTree();
                administrador.getLanzamientos();
            } catch (Exception e) {
                JOptionPane.showMessageDialog(wd_Artista, "Ingrese un valor valido que no se repita");
            }
            
            
        }
        jd_crearSingle.setVisible(false);
    }                                                

    private void bt_nuevaCancionMouseClicked(java.awt.event.MouseEvent evt) {                                             
        if (cualCrear == 2) {
            cuantasCanciones = Integer.parseInt(JOptionPane.showInputDialog("Cuantas canciones agregara?"));
        }
        referencia = Integer.parseInt(tf_lanzaId.getText());
        iniciarCrearCancion();

    }                                            

    private void bt_nuevaCancionActionPerformed(java.awt.event.ActionEvent evt) {                                                

    }                                               

    private void bt_newSongActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    public void iniciarjd_crearSingle() {
        jd_crearSingle.pack();
        jd_crearSingle.setModal(true);
        jd_crearSingle.setLocationRelativeTo(wd_Artista);
        jd_crearSingle.setVisible(true);
    }

    public void iniciarCrearCancion() {
        jd_crearCancion.pack();
        jd_crearCancion.setModal(true);
        jd_crearCancion.setLocationRelativeTo(wd_Artista);
        jd_crearCancion.setVisible(true);
    }

    public void iniciarVentanaArtista() {
        wd_Artista.pack();
        resetArtistTree();
        tf_titulo.setText("");
        tf_tiempo.setText("");
        sp_referencia.setVisible(false);
        tf_referencia.setVisible(false);
        this.setVisible(false);
        wd_Artista.setLocationRelativeTo(null);
        wd_Artista.setVisible(true);

    }

    public void resetArtistTree() {
        DefaultTreeModel m = (DefaultTreeModel) jt_lanzamientos.getModel();
        DefaultMutableTreeNode raiz = new DefaultMutableTreeNode("Lanzamientos");
        m.setRoot(raiz);
        DefaultMutableTreeNode albumes = new DefaultMutableTreeNode("Albumes");
        DefaultMutableTreeNode singles = new DefaultMutableTreeNode("Singles");
        raiz.add(albumes);
        raiz.add(singles);
        int i = 1;
        for (Lanzamiento l : ((Artista) actual).getLanzamiento()) {
            if (l instanceof Album) {
                DefaultMutableTreeNode temp = new DefaultMutableTreeNode(l);
                for (Cancion c : ((Album) l).getCanciones()) {
                    temp.add(new DefaultMutableTreeNode(c));
                }
                albumes.add(temp);
            } else {
                DefaultMutableTreeNode temp = new DefaultMutableTreeNode(l);

                temp.add(new DefaultMutableTreeNode(((Single) l).getCancion()));
                singles.add(temp);
            }
        }
        m.reload();

    }

    public void iniciarJd_register() {

        tf_artName.setEnabled(true);
        jd_register.pack();
        if (modify == 0) {

            tf_usuario.setText("");
            tf_pass.setText("");
            tf_artName.setText("");
            sp_edad.setValue(12);
        } else {
            tf_usuario.setText(actual.getUsername());
            tf_pass.setText(actual.getPassword());

            sp_edad.setValue(actual.getEdad());
            bt_create.setText("modificar");
            if (actual instanceof Oyente) {
                tf_artName.setEnabled(false);
            } else {
                tf_artName.setText(((Artista) actual).getNombreArtistico());
            }
        }
        jd_register.setModal(true);
        jd_register.setLocationRelativeTo(this);
        jd_register.setVisible(true);
    }

    public void iniciarjd_listar() {
        jd_listar.pack();
        if (wd_Cliente.isVisible()) {
            jd_listar.setLocationRelativeTo(wd_Cliente);
        } else if (wd_Artista.isVisible()) {
            jd_listar.setLocationRelativeTo(wd_Artista);
        }
        bt_eliminar.setVisible(false);
        jd_listar.setModal(true);
        jd_listar.setVisible(true);
    }

    public void iniciarVentanaCliente() {
        mb_menu2.add(mi_crudUsuarios);
        wd_Cliente.pack();
        this.setVisible(false);
        wd_Cliente.setLocationRelativeTo(null);
        wd_Cliente.setVisible(true);

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_crearLanzamiento;
    private javax.swing.JButton bt_create;
    private javax.swing.JButton bt_eliminar;
    private javax.swing.JButton bt_logIn;
    private javax.swing.JButton bt_logIn1;
    private javax.swing.JButton bt_newSong;
    private javax.swing.JButton bt_nuevaCancion;
    private com.toedter.calendar.JDateChooser dc_lanzamiento;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JDialog jd_crearCancion;
    private javax.swing.JDialog jd_crearSingle;
    private javax.swing.JDialog jd_listar;
    private javax.swing.JDialog jd_register;
    private javax.swing.JList<String> jl_listar;
    private javax.swing.JTree jt_lanzamientos;
    private javax.swing.JLabel lb_nombreArtista;
    private javax.swing.JLabel lb_titleSingles;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenuBar mb_menu2;
    private javax.swing.JMenu mi_crudLanzamiento;
    private javax.swing.JMenu mi_crudUsuarios;
    private javax.swing.JMenuItem mmi_Eliminar;
    private javax.swing.JMenuItem mmi_crearLanzamiento;
    private javax.swing.JMenuItem mmi_createSingle;
    private javax.swing.JMenuItem mmi_listEliminar;
    private javax.swing.JMenuItem mmi_modificar;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPanel pn_Artista;
    private javax.swing.JPanel pn_listar;
    private javax.swing.JPanel pn_login;
    private javax.swing.JPanel pn_register;
    private javax.swing.JSpinner sp_edad;
    private javax.swing.JSpinner sp_referencia;
    private javax.swing.JTextField tf_artName;
    private javax.swing.JTextField tf_lanzaId;
    private javax.swing.JTextField tf_lanzaName;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JTextField tf_pass;
    private javax.swing.JLabel tf_referencia;
    private javax.swing.JTextField tf_tiempo;
    private javax.swing.JTextField tf_titulo;
    private javax.swing.JTextField tf_usuario;
    private javax.swing.JFrame wd_Artista;
    private javax.swing.JFrame wd_Cliente;
    // End of variables declaration                   
}
