/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package lab6p2_darielsevilla;

/**
 *
 * @author HP
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        wd_Artista = new javax.swing.JFrame();
        pn_Artista = new javax.swing.JPanel();
        lb_nombreArtista = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTree1 = new javax.swing.JTree();
        mb_menu = new javax.swing.JMenuBar();
        mi_crudUsuarios = new javax.swing.JMenu();
        mi_crudCanciones = new javax.swing.JMenu();
        mi_crudLanzamiento = new javax.swing.JMenu();
        mi_crudListaReproduccion = new javax.swing.JMenu();
        wd_Cliente = new javax.swing.JFrame();
        jRadioButtonMenuItem1 = new javax.swing.JRadioButtonMenuItem();
        jMenuItem1 = new javax.swing.JMenuItem();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        tf_nombreUsuario = new javax.swing.JTextField();
        pf_password = new javax.swing.JPasswordField();
        bt_logIn = new javax.swing.JButton();
        bt_logIn1 = new javax.swing.JButton();
        bt_logIn2 = new javax.swing.JButton();

        pn_Artista.setBackground(new java.awt.Color(0, 0, 0));
        pn_Artista.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lb_nombreArtista.setBackground(new java.awt.Color(0, 204, 0));
        lb_nombreArtista.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        lb_nombreArtista.setForeground(new java.awt.Color(0, 204, 0));
        lb_nombreArtista.setText("Artista");
        pn_Artista.add(lb_nombreArtista, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, 86, 39));

        jTree1.setBackground(new java.awt.Color(255, 255, 255));
        jTree1.setForeground(new java.awt.Color(0, 0, 0));
        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Lanzamientos");
        jTree1.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane2.setViewportView(jTree1);

        pn_Artista.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 50, 436, -1));

        mi_crudUsuarios.setText("Usuarios");
        mb_menu.add(mi_crudUsuarios);

        mi_crudCanciones.setText("Canciones");
        mb_menu.add(mi_crudCanciones);

        mi_crudLanzamiento.setText("Lanzamientos");
        mb_menu.add(mi_crudLanzamiento);

        mi_crudListaReproduccion.setText("Listas de Reproduccion");
        mb_menu.add(mi_crudListaReproduccion);

        wd_Artista.setJMenuBar(mb_menu);

        javax.swing.GroupLayout wd_ArtistaLayout = new javax.swing.GroupLayout(wd_Artista.getContentPane());
        wd_Artista.getContentPane().setLayout(wd_ArtistaLayout);
        wd_ArtistaLayout.setHorizontalGroup(
            wd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Artista, javax.swing.GroupLayout.PREFERRED_SIZE, 602, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        wd_ArtistaLayout.setVerticalGroup(
            wd_ArtistaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pn_Artista, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout wd_ClienteLayout = new javax.swing.GroupLayout(wd_Cliente.getContentPane());
        wd_Cliente.getContentPane().setLayout(wd_ClienteLayout);
        wd_ClienteLayout.setHorizontalGroup(
            wd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        wd_ClienteLayout.setVerticalGroup(
            wd_ClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        jRadioButtonMenuItem1.setSelected(true);
        jRadioButtonMenuItem1.setText("jRadioButtonMenuItem1");

        jMenuItem1.setText("jMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 0, 0));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 204, 0));
        jLabel1.setText("SPOTIFY");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(209, 14, -1, -1));
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(228, 114, -1, -1));

        tf_nombreUsuario.setBackground(new java.awt.Color(255, 255, 255));
        tf_nombreUsuario.setForeground(new java.awt.Color(0, 0, 0));
        jPanel1.add(tf_nombreUsuario, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 305, -1));

        pf_password.setBackground(new java.awt.Color(255, 255, 255));
        pf_password.setForeground(new java.awt.Color(0, 0, 0));
        pf_password.setText("jPasswordField1");
        jPanel1.add(pf_password, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 200, 300, -1));

        bt_logIn.setBackground(new java.awt.Color(0, 204, 0));
        bt_logIn.setForeground(new java.awt.Color(0, 0, 0));
        bt_logIn.setText("Register");
        bt_logIn.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(bt_logIn, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 300, 100, 30));

        bt_logIn1.setBackground(new java.awt.Color(0, 204, 0));
        bt_logIn1.setForeground(new java.awt.Color(0, 0, 0));
        bt_logIn1.setText("Log in");
        bt_logIn1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(bt_logIn1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 100, 30));

        bt_logIn2.setBackground(new java.awt.Color(0, 0, 153));
        bt_logIn2.setText("Log in");
        bt_logIn2.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jPanel1.add(bt_logIn2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 250, 100, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 527, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>                        

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton bt_logIn;
    private javax.swing.JButton bt_logIn1;
    private javax.swing.JButton bt_logIn2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JMenuItem jMenuItem1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JRadioButtonMenuItem jRadioButtonMenuItem1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTree jTree1;
    private javax.swing.JLabel lb_nombreArtista;
    private javax.swing.JMenuBar mb_menu;
    private javax.swing.JMenu mi_crudCanciones;
    private javax.swing.JMenu mi_crudLanzamiento;
    private javax.swing.JMenu mi_crudListaReproduccion;
    private javax.swing.JMenu mi_crudUsuarios;
    private javax.swing.JPasswordField pf_password;
    private javax.swing.JPanel pn_Artista;
    private javax.swing.JTextField tf_nombreUsuario;
    private javax.swing.JFrame wd_Artista;
    private javax.swing.JFrame wd_Cliente;
    // End of variables declaration                   
}
